### ISSUE TITLE
Secunet - Problem with Plugin

### ISSUE THREAD

**Issue by bad13** [Kleinrotti/checkmk_telematik#5]
Hi,

thank you for your work! I am just try to use your Plugin but i am not able to get it up and running. I used different ports (443|8500) but it won't work. Maybe you could give me a hint? Remotemanagement is enabled.

LOGS:

#Port 443

OMD[mysite]:~$ cmk -d 172.20.xxx.xxx
ERROR [special_telematik_konnektor]: Agent exited with code 1: Traceback (most recent call last):
  File "/omd/sites/mysite/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/omd/sites/mysite/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/omd/sites/mysite/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/omd/sites/mysite/lib/python3.9/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/omd/sites/mysite/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "/omd/sites/mysite/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "/omd/sites/mysite/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/omd/sites/mysite/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/omd/sites/mysite/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/omd/sites/mysite/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/omd/sites/mysite/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/omd/sites/mysite/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='172.20.xxx.xxx', port=8500): Max retries exceeded with url: /ws/CardService (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/omd/sites/mysite/local/share/check_mk/agents/special/agent_telematik_konnektor", line 482, in <module>
    main(args)
  File "/omd/sites/mysite/local/share/check_mk/agents/special/agent_telematik_konnektor", line 437, in main
    cardResponse = requestCards()
  File "/omd/sites/mysite/local/share/check_mk/agents/special/agent_telematik_konnektor", line 148, in requestCards
    return request(f"https://{host}:{port}/ws/CardService", body)
  File "/omd/sites/mysite/local/share/check_mk/agents/special/agent_telematik_konnektor", line 219, in request
    response = requests.post(url, headers={"Content-Type": "text/xml"},
  File "/omd/sites/mysite/lib/python3.9/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/omd/sites/mysite/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/omd/sites/mysite/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/omd/sites/mysite/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/omd/sites/mysite/lib/python3.9/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='172.20.xxx.xxx', port=8500): Max retries exceeded with url: /ws/CardService (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)')))

#port 8500

OMD[mysite]:~$ cmk -d 172.20.xxx.xxx -v
[ProgramFetcher] Execute data source
ERROR [special_telematik_konnektor]: Agent exited with code 1: Traceback (most recent call last):
  File "/omd/sites/mysite/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/omd/sites/mysite/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/omd/sites/mysite/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/omd/sites/mysite/lib/python3.9/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/omd/sites/mysite/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "/omd/sites/mysite/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "/omd/sites/mysite/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/omd/sites/mysite/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/omd/sites/mysite/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/omd/sites/mysite/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/omd/sites/mysite/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/omd/sites/mysite/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='172.20.xxx.xxx', port=8500): Max retries exceeded with url: /ws/CardService (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/omd/sites/mysite/local/share/check_mk/agents/special/agent_telematik_konnektor", line 482, in <module>
    main(args)
  File "/omd/sites/mysite/local/share/check_mk/agents/special/agent_telematik_konnektor", line 437, in main
    cardResponse = requestCards()
  File "/omd/sites/mysite/local/share/check_mk/agents/special/agent_telematik_konnektor", line 148, in requestCards
    return request(f"https://{host}:{port}/ws/CardService", body)
  File "/omd/sites/mysite/local/share/check_mk/agents/special/agent_telematik_konnektor", line 219, in request
    response = requests.post(url, headers={"Content-Type": "text/xml"},
  File "/omd/sites/mysite/lib/python3.9/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/omd/sites/mysite/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/omd/sites/mysite/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/omd/sites/mysite/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/omd/sites/mysite/lib/python3.9/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='172.20.xxx.xxx', port=8500): Max retries exceeded with url: /ws/CardService (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)')))
[PiggybackFetcher] Execute data source
No piggyback files for '172.20.xxx.xxx'. Skip processing.
No piggyback files for '172.20.xxx.xxx'. Skip processing.
No piggyback files for '172.20.xxx.xxx'. Skip processing.
No piggyback files for '172.20.xxx.xxx'. Skip processing.

**Comment by Kleinrotti** [comment]
Due to the error message, I think you turned on SSL verification in the plugin settings but you didn't import the CA from the Konnektor.
`ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)`

Ether you leave the SSL verification disabled or you have to import the CA in the checkmk operating system.

**Comment by bad13** [comment]
Thank you for your fast reaction. After disableing SS-Verify:
Get the Got no valid response from konnektor.Code: 404 Message

https://github.com/Kleinrotti/checkmk_telematik/issues/3#issuecomment-1675840707

**Comment by Kleinrotti** [comment]
Please try debugging with Postman ->https://github.com/Kleinrotti/checkmk_telematik/issues/3#issuecomment-1582853717

**Comment by Kleinrotti** [comment]
But as far as I can tell, error 404 means that the connection couldn't be established.
Is there maybe a firewall in between? Or has the Konnektor client authentication enabled?
